"""name = input("What is your name?\n")
surname = input("What is your surname?\n")
year = input("What is your College Years?\n")
code = input("What is your Student ID number?\n")
print("Welcome to Python world")
print("Hi,%s"%name)
print("%s."%surname)
print("Your College Year is,%s."%year)
print("ํYour Student ID number is,%s."%code)
print("Hope you are happy")"""
"""
x = 20
y = 35.24
z = 1j
a = float(x)
b = int(y)
c = complex(x)
print("%s"%a)
print("%s"%b)
print("%s"%c)
"""
n1 = input("Input Your First Number:\n")
n2 = input("Input Your Second Number:\n")
n3 = input("Input Your Third Number:\n")
n4 = input("Input Your Fourth Number:\n")
n5 = input("Input Your Fifth Number:\n")
a = float(n1)
b = complex(n1)
c = float(n2)
d = complex(n2)
e = float(n3)
f = complex(n3)
g = float(n4)
h = complex(n4)
i = float(n5)
j = complex(n5)
print("Float of %s"%n1)
print("Equal %s"%a)
print("Complex of %s"%n1)
print("Equal %s"%b)
print("Float of %s"%n2)
print("Equal %s"%c)
print("Complex of %s"%n2)
print("Equal %s"%d)
print("Float of %s"%n3)
print("Equal %s"%e)
print("Complex of %s"%n3)
print("Equal %s"%f)
print("Float of %s"%n4)
print("Equal %s"%g)
print("Complex of %s"%n4)
print("Equal %s"%h)
print("Float of %s"%n5)
print("Equal %s"%i)
print("Complex of %s"%n5)
print("Equal %s"%j)